# Generated by Django 5.1.5 on 2025-02-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0002_teamsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название выполненной работы'),
        ),
        migrations.AlterField(
            model_name='teamsection',
            name='photo',
            field=models.ImageField(upload_to='team_person_foto/', verbose_name='Фото сотрудника'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(related_name='portfolio_items', to='content_manager.portfoliocategory', verbose_name='Категории'),
        ),
    ]
